[package]
name = "risor-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "CLI for the Risor scripting language"

[[bin]]
name = "risor"
path = "src/main.rs"

[dependencies]
risor = { path = "../risor" }
rustyline = "15"
